version: '3.4'

volumes:
  db-data: {}

services:

  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - api
    volumes:
      - ./api/default.conf:/etc/nginx/conf.d/default.conf
      - ./api/public:/var/www/api/public:ro
    ports:
      - "8080:80"

  api:
    build: ./api
    depends_on:
      - db
    volumes:
      - ./api/:/var/www/api
      - /var/www/api/vendor
    environment:
      - APP_NAME
      - APP_ENV
      - APP_KEY
      - APP_DEBUG
      - APP_URL
      - APP_TIMEZONE
      - LOG_CHANNEL
      - LOG_SLACK_WEBHOOK_URL
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - CACHE_DRIVER
      - QUEUE_CONNECTION

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql:rw
    expose:
      - "${DB_PORT}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080